[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
]

[advisories]
version = 2
# No fix for RSA, and this is a dependency from ssh_key crate to handle rsa ssh key.
# https://rustsec.org/advisories/RUSTSEC-2023-0071
ignore = ["RUSTSEC-2023-0071"]

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"
version = "1.0.3"

[bans]
multiple-versions = "deny"
skip-tree = [
    { name = "bitflags" },
    # this is only needed for notify: https://github.com/notify-rs/notify/issues/648
    { name = "mio" },
    # this is needed for:
    #  `bwrap v1.3.0` (https://github.com/micl2e2/bwrap/pull/4)
    #  `unicode-truncate v1.1.0` (https://github.com/Aetf/unicode-truncate/pull/23)
    { name = "unicode-width" },
]
