[package]
name = "asyncgit"
version = "0.1.8"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"
description = "allow using git2 in a asynchronous context"
homepage = "https://gitui.org"
readme = "README.md"
license = "MIT"
categories = ["concurrency","asynchronous"]

[dependencies]
git2 = { version = "0.13.4", default-features = false }
rayon-core = "1.7"
crossbeam-channel = "0.4"
log = "0.4"
is_executable = "0.1"
scopetime = { path = "../scopetime", version = "0.1" }
tempfile = "3.1"